Delete User Endpoint
alkemyTech/OT263-server pull request #11
Opened 2022-08-28 05:51 UTC by pablopastorino

### Description

- Adds delete user endpoint
- Adds endpoint tests

### Issue
[OT263-45](https://alkemy-labs.atlassian.net/browse/OT263-45?atlOrigin=eyJpIjoiNGMyY2EzN2M3MThhNGQ1MmE0ZGUwOTFiMTE2ZmYzZmYiLCJwIjoiaiJ9)

### Evidence
![OT263-45](https://user-images.githubusercontent.com/69921834/187059693-fd5a6b99-1996-4ca4-8c03-64c964b25432.png)

2022-09-01 14:04 UTC, GauntStrelok requested changes
Responde las preguntas que te puse
Fijate que me estas generando conflictos porque estas haciendo un formatting diferente, vas a tener que hacer pull de main para arreglar esos conflictos.
Habla con tus companieros para decidir que formatting usan todos.

2022-09-01 14:04 UTC, GauntStrelok commented on controllers/user.controller.js
> +			if (id != req.params.id) return res.status(403).json(createError.Forbidden())
Que es lo que hace este if aca?

2022-09-01 14:04 UTC, GauntStrelok commented on package.json
>  {
no esta bueno que modifiques todo el package.json, aunque sea el formatter, el problema es que genera conflictos en los merges que no sirven de nada

2022-09-01 19:10 UTC, pablopastorino commented on controllers/user.controller.js
> +			if (id != req.params.id) return res.status(403).json(createError.Forbidden())
Eliminado, no se porque estaba.

2022-09-01 19:12 UTC, pablopastorino commented on package.json
>  {
Bien, lo que modifiqué era el script de los test pero el formateo movio todo. Resuelto.

2022-09-07 09:23 UTC, GauntStrelok commented on models/user.js
> +<<<<<<< HEAD
Mal mergeado, arreglar

2022-09-07 09:23 UTC, GauntStrelok commented on routes/users.js
> +<<<<<<< HEAD
Mal mergeado, arreglar

2022-09-07 15:35 UTC, pablopastorino commented on models/user.js
> +<<<<<<< HEAD
Corregido.

2022-09-09 10:01 UTC, GauntStrelok commented on routes/users.js
> +<<<<<<< HEAD
.

2022-09-09 18:12 UTC, pablopastorino commented
Corregido.

2022-09-15 07:42 UTC, merged